In [35]:
#Numpy is fast because it is built upon C and C++

import numpy as np


a=[1,2,3,4,5]
a=np.array(a)

print(type(a))
print(a)
print(a.shape)


<class 'numpy.ndarray'>
[1 2 3 4 5]
(5,)


In [55]:
b=np.array([[1,2,3],[4,5,6]])
print("b is ",b)
print(b.shape)
print("Number of rows are",b.ndim)
c=np.zeros((3,4))
print(c)
d=np.ones((4,4))
print(d)
e=np.full((4,5),45)
print(e)
f=np.full_like((e),34)
print(f)
print(np.random.rand(3,4))
print(np.random.random_sample(b.shape))
print(np.random.randint(1,100,size=(2,2)))
print(np.random.randint(1,100,6).reshape(2,3))
print(np.identity (4))
b=a.copy() # Imp to copy 
print("a is ",b)      
print("Multiplication of a and b is ",np.matmul(a,b))


b is  [[1 2 3]
 [4 5 6]]
(2, 3)
Number of rows are 2
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]]
[[34 34 34 34 34]
 [34 34 34 34 34]
 [34 34 34 34 34]
 [34 34 34 34 34]]
[[0.76030899 0.85946653 0.00851305 0.86810267]
 [0.97792317 0.76573265 0.51088617 0.27002916]
 [0.98188983 0.93704578 0.88146836 0.92907109]]
[[0.20818159 0.89181944 0.48108332]
 [0.18415154 0.33096073 0.25766524]]
[[95 52]
 [21 62]]
[[16 23 22]
 [87 17 13]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
a is  [1, 2, 3, 4]
Multiplication of a and b is  30


In [51]:
a=[1,2,3,4]
b=[4,5,6,5]
c=[7,8,9,6]

d=np.array([a,b,c])
print(d)
print(d.shape)

print(d<=3)
print(d[d<3])

d=d.reshape(4,3)
print(d)
print(np.arange(1,10,3))
print(np.linspace(1,10,19))



[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 6]]
(3, 4)
[[ True  True  True False]
 [False False False False]
 [False False False False]]
[1 2]
[[1 2 3]
 [4 4 5]
 [6 5 7]
 [8 9 6]]
[1 4 7]
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]
