In [49]:
import numpy as np
a=[1,2,3,4,5,6]
a=np.array(a)
a=a.reshape(3,2)
print(a.shape[0])
print(a)
print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.full((3,4),20))
print(np.random.rand(3,4))
print(np.random.randint(1,100,6).reshape(2,3))
print(np.random.randint(5,10,3))
print(np.identity((3)))
b=[1,2,3]
c=[4,5,6]
d=np.array([b,c])
print(d<4)
print(np.arange(10))
print(np.arange(2,10,5))
print(np.linspace(0,20,5))



3
[[1 2]
 [3 4]
 [5 6]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[20 20 20 20]
 [20 20 20 20]
 [20 20 20 20]]
[[0.24532911 0.15377871 0.5869652  0.57505282]
 [0.62004657 0.78680987 0.93049446 0.69846985]
 [0.25806297 0.74735028 0.80275177 0.28829557]]
[[63 73 33]
 [20 40 77]]
[9 9 7]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ True  True  True]
 [False False False]]
[0 1 2 3 4 5 6 7 8 9]
[2 7]
[ 0.  5. 10. 15. 20.]
