# Pandas template

#### Importing and creating a Dataframe

In [ ]:
import pandas as pd
import numpy as np

np.arange(5,10)

df=pd.DataFrame(np.arange(1,21).reshape(5,4),index=['r1','r2','r3','r4','r5'],columns=['c1','c2','c3','c4'])
print(df)

#### Getting data back from a Dataframe

In [7]:
a=(df.loc['r1',['c1','c2']]) #Loc returns dataseries
print(a)
print(type(a)) #Single row or column is a series
print(df.iloc[:,:]) #iloc returns dataframe 
df['c2'] #Directly type col name
df[['c2','c3']] #Directly type col name

c1    1
c2    2
Name: r1, dtype: int64
<class 'pandas.core.series.Series'>
    c1  c2  c3  c4
r1   1   2   3   4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16
r5  17  18  19  20


c2  c3
r1   2   3
r2   6   7
r3  10  11
r4  14  15
r5  18  19

#### Some more useful functions (df into array, checking nulls, unique values)

In [9]:
print(df.values) # converts dataframe into an array
df.isnull()
df.isnull().sum()
df['c1'].value_counts()
df['c1'].unique()

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


array([ 1,  5,  9, 13, 17])

#### Create Dataframe from csv, Filter

In [58]:
df=pd.read_csv('segment.csv')
df.head()
df.shape
df.isnull().sum()
#df.info()
#df.describe()  # This function skips categorical features
df['Married'].value_counts()
df[df['Kids']>2]
df1=pd.read_csv('segment.csv',index_col='User ID',usecols=['User ID','Gender','Age','Kids'],dtype={'User ID':str,'Gender':str,'Age':int,'Kids':int})
print(df1.head())
df1.to_csv('temp_segment_can_delete.csv')

         Gender  Age  Kids
User ID                   
1        Female   65     1
2          Male   42     2
3           NaN   21     5
4          Male   15     0
5        Female   32     0


#### Create Dataframe from json

In [89]:
data='[{"Name":"Nitin","Age":"35","job_profile":[{"company":"News","position":"Data Product Manager"}]},{"Name":"Nikita","Age":"35","job_profile":[{"company":"News","position":"Data Product Manager"}]}]'
df=pd.read_json(data)

In [90]:
df

Name  Age                                        job_profile
0   Nitin   35  [{'company': 'News', 'position': 'Data Product...
1  Nikita   35  [{'company': 'News', 'position': 'Data Product...

In [92]:
df.to_json(orient="records")

'[{"Name":"Nitin","Age":35,"job_profile":[{"company":"News","position":"Data Product Manager"}]},{"Name":"Nikita","Age":35,"job_profile":[{"company":"News","position":"Data Product Manager"}]}]'

#### Create Dataframe from tables in html

In [94]:
pd.read_html('https://www.asx.com.au/asx/research/listedCompanies.do')

[                       Company name ASX code               GICS industry group
 0                               NaN      NaN                               NaN
 1              A-CAP ENERGY LIMITED      ACB                            Energy
 2    A1 INVESTMENTS & RESOURCES LTD      AYI            Diversified Financials
 3             A2B AUSTRALIA LIMITED      A2B                    Transportation
 4             ABACUS PROPERTY GROUP      ABP                       Real Estate
 ..                              ...      ...                               ...
 241            AWN HOLDINGS LIMITED      AWN                     Capital Goods
 242            AXIOM MINING LIMITED      AVQ                         Materials
 243        AXIOM PROPERTIES LIMITED      AXI                       Real Estate
 244        AZURE HEALTHCARE LIMITED      AZV  Health Care Equipment & Services
 245          AZURE MINERALS LIMITED      AZS                         Materials
 
 [246 rows x 3 columns]]